//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Big_C
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiNhanh
    {
        public ChiNhanh()
        {
            this.Luongs = new HashSet<Luong>();
            this.QuanLies = new HashSet<QuanLy>();
        }
    
        public string MaChiNhanh { get; set; }
        public string TenChiNhanh { get; set; }
        public string DiaChi { get; set; }
    
        public virtual ICollection<Luong> Luongs { get; set; }
        public virtual ICollection<QuanLy> QuanLies { get; set; }
    }
}
