//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Big_C
{
    using System;
    using System.Collections.Generic;
    
    public partial class Luong
    {
        public string MaNhanVien { get; set; }
        public string MaLuong { get; set; }
        public string MaQuanLy { get; set; }
        public string MaChiNhanh { get; set; }
        public Nullable<int> Luong1 { get; set; }
        public Nullable<double> Thue { get; set; }
        public Nullable<double> ChietKhau { get; set; }
        public Nullable<int> TongLuong { get; set; }
    
        public virtual ChiNhanh ChiNhanh { get; set; }
        public virtual QuanLy QuanLy { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
