//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Big_C
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public NhanVien()
        {
            this.Luongs = new HashSet<Luong>();
        }
    
        public string MaNhanVien { get; set; }
        public string TenNhanVien { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public string DiaChi { get; set; }
        public string SDT { get; set; }
        public string CCCD { get; set; }
        public System.DateTime NgayVaoLam { get; set; }
        public Nullable<int> SoNgayLam { get; set; }
        public string MaQuanLy { get; set; }
    
        public virtual ICollection<Luong> Luongs { get; set; }
        public virtual QuanLy QuanLy { get; set; }
    }
}
