//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Big_C
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuanLy
    {
        public QuanLy()
        {
            this.Luongs = new HashSet<Luong>();
            this.NhanViens = new HashSet<NhanVien>();
        }
    
        public string MaQuanLy { get; set; }
        public string TenQuanLy { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public string DiaChi { get; set; }
        public string SDT { get; set; }
        public string CCCD { get; set; }
        public System.DateTime NgayVaoLam { get; set; }
        public Nullable<int> SoNgayLam { get; set; }
        public string MaChiNhanh { get; set; }
        public Nullable<int> SoNhanVienQuanLy { get; set; }
    
        public virtual ChiNhanh ChiNhanh { get; set; }
        public virtual ICollection<Luong> Luongs { get; set; }
        public virtual ICollection<NhanVien> NhanViens { get; set; }
    }
}
